import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      style={{ background: '#e6d6fa' }}
    >
      <body className="min-h-full flex bg-gradient-to-br from-[#ede9fe] via-[#f3e8ff] to-[#e0e7ff]">
        <aside className="w-80 min-h-screen bg-gradient-to-b from-[#8f2be2] via-[#6366f1] to-[#312e81] flex flex-col gap-6 shadow-2xl relative z-10 border-r-4 border-[#312e81]">
          <div className="text-4xl font-extrabold text-white mb-8 text-center tracking-wide py-8 select-none rounded-b-3xl shadow-lg bg-gradient-to-r from-[#8f2be2] to-[#6366f1] border-b-4 border-white">
            <span className="inline-block skew-x-[-8deg] tracking-widest drop-shadow-[2px_2px_0_#312e81]">No Filter</span>
          </div>
          <nav className="flex flex-col gap-3 text-lg font-semibold px-4">
            <a href="/" className="block text-white bg-gradient-to-r from-[#8f2be2] to-[#6366f1] rounded-xl px-6 py-4 mb-2 shadow-lg border-2 border-[#312e81] hover:bg-white hover:text-[#312e81] hover:scale-105 hover:border-[#8f2be2] transition-all font-bold">🏠 Home</a>
            <a href="/courses" className="block text-white bg-gradient-to-r from-[#8f2be2] to-[#6366f1] rounded-xl px-6 py-4 mb-2 shadow-lg border-2 border-[#312e81] hover:bg-white hover:text-[#312e81] hover:scale-105 hover:border-[#8f2be2] transition-all font-bold">📚 Modules</a>
            <a href="/ai-tutor" className="block text-white bg-gradient-to-r from-[#8f2be2] to-[#6366f1] rounded-xl px-6 py-4 mb-2 shadow-lg border-2 border-[#312e81] hover:bg-white hover:text-[#312e81] hover:scale-105 hover:border-[#8f2be2] transition-all font-bold">🤖 AI Tutor</a>
            <a href="/about" className="block text-white bg-gradient-to-r from-[#8f2be2] to-[#6366f1] rounded-xl px-6 py-4 mb-2 shadow-lg border-2 border-[#312e81] hover:bg-white hover:text-[#312e81] hover:scale-105 hover:border-[#8f2be2] transition-all font-bold">ℹ️ About</a>
            <a href="/features" className="block text-white bg-gradient-to-r from-[#8f2be2] to-[#6366f1] rounded-xl px-6 py-4 mb-2 shadow-lg border-2 border-[#312e81] hover:bg-white hover:text-[#312e81] hover:scale-105 hover:border-[#8f2be2] transition-all font-bold">✨ Features</a>
            <a href="/contact" className="block text-white bg-gradient-to-r from-[#8f2be2] to-[#6366f1] rounded-xl px-6 py-4 mb-2 shadow-lg border-2 border-[#312e81] hover:bg-white hover:text-[#312e81] hover:scale-105 hover:border-[#8f2be2] transition-all font-bold">✉️ Contact</a>
            <a href="/login" className="block text-white bg-gradient-to-r from-[#8f2be2] to-[#6366f1] rounded-xl px-6 py-4 mb-2 shadow-lg border-2 border-[#312e81] hover:bg-white hover:text-[#312e81] hover:scale-105 hover:border-[#8f2be2] transition-all font-bold">🔑 Login</a>
          </nav>
        </aside>
        <main className="flex-1 flex flex-col min-h-screen bg-transparent">{children}</main>
      </body>
    </html>
  );
}
